//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademiaNV
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class academiaEntities1 : DbContext
    {
        public academiaEntities1()
            : base("name=academiaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_aluno> tb_aluno { get; set; }
        public virtual DbSet<tb_aula> tb_aula { get; set; }
        public virtual DbSet<tb_fisioterapeuta> tb_fisioterapeuta { get; set; }
        public virtual DbSet<tb_funcionario> tb_funcionario { get; set; }
        public virtual DbSet<tb_funcionario_funcao> tb_funcionario_funcao { get; set; }
        public virtual DbSet<tb_instrutor> tb_instrutor { get; set; }
        public virtual DbSet<tb_pagamento> tb_pagamento { get; set; }
        public virtual DbSet<tb_tipo_atividade> tb_tipo_atividade { get; set; }
        public virtual DbSet<tb_tipo_plano> tb_tipo_plano { get; set; }
    }
}
