//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademiaNV
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_aula
    {
        public int IdAula { get; set; }
        public string Nome { get; set; }
        public System.TimeSpan HoraInicio { get; set; }
        public System.TimeSpan HoraFim { get; set; }
        public int IdInstrutor { get; set; }
        public int IdTipoAula { get; set; }
        public bool DiaSegunda { get; set; }
        public bool DiaTerca { get; set; }
        public bool DiaQuarta { get; set; }
        public bool DiaQuinta { get; set; }
        public bool DiaSexta { get; set; }
        public bool DiaSabado { get; set; }
    }
}
