//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademiaNV
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_funcionario
    {
        public int IdFuncionario { get; set; }
        public string Nome { get; set; }
        public string RG { get; set; }
        public string CPF { get; set; }
        public int Funcao { get; set; }
        public string Login { get; set; }
        public string Senha { get; set; }
    }
}
