//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademiaNV
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pagamento
    {
        public int IdPagamento { get; set; }
        public int IdAluno { get; set; }
        public int IdTipoPlano { get; set; }
        public System.DateTime DataPagamento { get; set; }
        public System.DateTime DataProximoPagamento { get; set; }
        public string Situacao { get; set; }
    }
}
