//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademiaNV
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tipo_plano
    {
        public int IdTipoPlano { get; set; }
        public string DescricaoPlano { get; set; }
    }
}
